"""Add notifications table

Revision ID: 79d021df2315
Revises: 003_add_profile_photo
Create Date: 2025-12-21 03:21:05.277965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d021df2315'
down_revision: Union[str, None] = '003_add_profile_photo'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_appointments_date', table_name='appointments')
    op.drop_index('ix_appointments_doctor_id', table_name='appointments')
    op.drop_index('ix_appointments_patient_id', table_name='appointments')
    op.drop_index('ix_appointments_status', table_name='appointments')
    op.alter_column('tokens', 'token',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.drop_index('ix_tokens_user_id', table_name='tokens')
    # op.drop_constraint('tokens_token_key', 'tokens', type_='unique')
    op.execute("ALTER TABLE tokens DROP CONSTRAINT IF EXISTS tokens_token_key")
    op.drop_index('ix_tokens_token', table_name='tokens')
    op.create_index(op.f('ix_tokens_token'), 'tokens', ['token'], unique=True)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_tokens_token'), table_name='tokens')
    op.create_index('ix_tokens_token', 'tokens', ['token'], unique=False)
    op.create_unique_constraint('tokens_token_key', 'tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_tokens_user_id', 'tokens', ['user_id'], unique=False)
    op.alter_column('tokens', 'token',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.create_index('ix_appointments_status', 'appointments', ['status'], unique=False)
    op.create_index('ix_appointments_patient_id', 'appointments', ['patient_id'], unique=False)
    op.create_index('ix_appointments_doctor_id', 'appointments', ['doctor_id'], unique=False)
    op.create_index('ix_appointments_date', 'appointments', ['appointment_date'], unique=False)
    op.drop_table('notifications')
    # ### end Alembic commands ###
